"""add user_id & company to sessions

Revision ID: e6fd101d9bd0
Revises: ac6c44fb3d87
Create Date: 2025-08-10 16:47:57.289172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fd101d9bd0'
down_revision: Union[str, Sequence[str], None] = 'ac6c44fb3d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
