services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipass
      POSTGRES_DB: ai_interview
    ports:
      - '5433:5432' # ← 로컬 포트 5433로 매핑
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8
    ports:
      - '5050:80'
volumes:
  pgdata:
